// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbGp9AIboRsU79I74WRVY14Ni-_2JbQss',
    appId: '1:1003239985728:web:5c60571629eeeb3d64c5a5',
    messagingSenderId: '1003239985728',
    projectId: 'childrenmusteat',
    authDomain: 'childrenmusteat.firebaseapp.com',
    storageBucket: 'childrenmusteat.appspot.com',
    measurementId: 'G-YT7SMR710X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQf_4hPgl-t3aUmYyspuhW3jLcuydQvvE',
    appId: '1:1003239985728:android:a06f2175f72b11d364c5a5',
    messagingSenderId: '1003239985728',
    projectId: 'childrenmusteat',
    storageBucket: 'childrenmusteat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrGZXLHiQF0t7J9YqMthoYup4zFM3AZTQ',
    appId: '1:1003239985728:ios:98775080d063053664c5a5',
    messagingSenderId: '1003239985728',
    projectId: 'childrenmusteat',
    storageBucket: 'childrenmusteat.appspot.com',
    iosClientId: '1003239985728-jq0kd58gfnnnvhtn66nbl4iq3bc8836b.apps.googleusercontent.com',
    iosBundleId: 'com.example.eatForKids',
  );
}
